WSRS-SWAFO/Controllers/EncodeController.cs
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using WSRS_SWAFO.Data;
using WSRS_SWAFO.Models;
using WSRS_SWAFO.ViewModels;
using WSRS_SWAFO.Interfaces;
using Hangfire;
using WSRS_SWAFO.Data.Enum;
using WSRS_SWAFO.Dtos;

namespace WSRS_SWAFO.Controllers
{
    [Authorize(Roles = "AppRole.Admin")]
    public class EncodeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<EncodeController> _logger;
        private readonly IEmailSender _emailSender;
        private readonly IHttpClientFactory _httpClientFactory;

        public EncodeController(ApplicationDbContext context, ILogger<EncodeController> logger, IEmailSender emailSender, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _logger = logger;
            _emailSender = emailSender;
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(EncodingMode));
        }

        // Mode Switch
        // Ticks whether Student Violation or Traffic Violation
        public IActionResult EncodingMode()
        {
            var referer = Request.Headers["Referer"].ToString();
            if (string.IsNullOrEmpty(referer))
            {
                return Content("<script>alert('External links are disabled. Use the in-app interface to proceed.'); window.history.back();</script>", "text/html");
            }
            return View();
        }

        // Page One - Student Violation Controller
        // Checks Student Record Database upon page load - Index
        [HttpPost]
        [HttpGet] // Adding for optional
        public async Task<IActionResult> StudentRecordViolation(string violationType = null)
        {
            if (HttpContext.Request.Method == HttpMethods.Post)
            {
                // Store the violation type in session or view data if needed
                HttpContext.Session.SetString("ViolationType", violationType);
            }

            // Checks student data in the Database
            var students = await _context.Students
                .Select(student => new StudentRecordViewModel
                {
                    // For every student in the Database, compiler creates the query
                    StudentNumber = student.StudentNumber,
                    LastName = student.LastName,
                    FirstName = student.FirstName
                })
                .AsNoTracking()
                .Take(5)
                .ToListAsync();

            TempData["ViolationType"] = violationType; // for pill indicator
            // Returns queried list
            return View(students.AsQueryable());
        }

        // Search Student - GET Function
        [HttpGet]
        public IActionResult Search(string searchStudent)
        {
            // Checks searchStudent
            if (!string.IsNullOrEmpty(searchStudent))
            {
                var studentsQuery = _context.Students.AsQueryable();
                // Compiler creates query for searchStudent
                if (int.TryParse(searchStudent, out int studentNumber))
                {
                    studentsQuery = studentsQuery.Where(s => s.StudentNumber == studentNumber);
                }
                else
                {
                    studentsQuery = studentsQuery.Where(s => s.LastName.Contains(searchStudent) || s.FirstName.Contains(searchStudent));
                }

                // Once existed, compiler creates table query
                var ExistingStudent = studentsQuery.Select(s => new StudentRecordViewModel
                {
                    StudentNumber = s.StudentNumber,
                    LastName = s.LastName,
                    FirstName = s.FirstName
                });
                return View(nameof(StudentRecordViolation), ExistingStudent);
            }
            return View(nameof(StudentRecordViolation), null);
        }

        // Page 2 - Create Student Data (If no student present) - Index
        [HttpGet]
        public IActionResult CreateStudentRecord(
            int? studentNumber,
            string? firstName,
            string? lastName)
        {
            var referer = Request.Headers["Referer"].ToString();
            if (string.IsNullOrEmpty(referer))
            {
                return RedirectToAction(nameof(StudentRecordViolation));
            }

            if (HttpContext.Session.GetString("ViolationType") is string violationType &&
                violationType == "Traffic Violation")
            {
                TempData["FromTraffic"] = true;
            }

            return View();
        }

        // Create Student Entry - POST Function
        [HttpPost]
        public async Task<IActionResult> CreateNewStudent(StudentRecordViewModel model, bool fromPending = false, bool fromTraffic = false)
        {
            if (!ModelState.IsValid)
            {
                SetToastMessage(message: "Please fill in the required fields appropriately.");
                return View(nameof(CreateStudentRecord), model);
            }

            var student = new Student
            {
                StudentNumber = model.StudentNumber,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email.ToLower()
            };

            try
            {
                _context.Students.Add(student);
                await _context.SaveChangesAsync();
                SetToastMessage(title: "Success", message: "A student was registered successfully.");
            }
            catch (Exception ex)
            {
                SetToastMessage(title: "Error", message: "Something went wrong while submitting your data.", cssClassName: "bg-danger text-white");
                _logger.LogError(ex.Message);
            }

            if (fromPending)
            {
                return RedirectToAction(nameof(Pending));
            }

            var redirect = fromTraffic ? nameof(EncodeTrafficViolation) : nameof(EncodeStudentViolation);

            return RedirectToAction(redirect, new
            {
                studentNumber = student.StudentNumber,
                firstName = student.FirstName,
                lastName = student.LastName
            });
        }

        // Checks whether studentID is existing or not - POST, GET Function
        [AcceptVerbs("GET", "POST")]
        public async Task<IActionResult> CheckStudentID(StudentRecordViewModel model)
        {
            var exists = await _context.Students.AnyAsync(student => student.StudentNumber == model.StudentNumber);
            return Json(!exists);
        }

        public IActionResult RedirectToView(
            [FromQuery] int studentNumber,
            [FromQuery] string firstName,
            [FromQuery] string lastName)
        {
            var violationType = HttpContext.Session.GetString("ViolationType");

            if (string.IsNullOrEmpty(violationType))
            {
                return RedirectToAction(nameof(EncodingMode));
            }

            if (violationType == "Student Violation")
            {
                return RedirectToAction(nameof(EncodeStudentViolation), new
                {
                    studentNumber,
                    firstName,
                    lastName
                });
            }

            if (violationType == "Traffic Violation")
            {
                return RedirectToAction(nameof(EncodeTrafficViolation), new
                {
                    studentNumber,
                    firstName,
                    lastName
                });
            }

            // Redirect to first page if no mode is selected
            return RedirectToAction(nameof(EncodingMode));
        }

        // Page 3 - Encode Student Violation (If student data exist)
        public IActionResult EncodeStudentViolation(
            [FromQuery] int studentNumber,
            [FromQuery] string firstName,
            [FromQuery] string lastName,
            [FromQuery] string? course = null,
            [FromQuery] string? collegeId = null,
            [FromQuery] string? note = null)
        {
            var referer = Request.Headers["Referer"].ToString();
            if (string.IsNullOrEmpty(referer))
            {
                return RedirectToAction(nameof(StudentRecordViolation));
            }

            var studentInfo = new ReportEncodedViewModel
            {
                StudentNumber = studentNumber,
                FirstName = firstName,
                LastName = lastName,
                Course = course,
                CollegeID = collegeId,
                Note = note,
            };

            ViewBag.Colleges = _context.College.ToList();

            return View(studentInfo);
        }

        // Creates a violation record - POST Function
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EncodeStudentViolation(ReportEncodedViewModel reportEncodedVM)
        {
            if (!ModelState.IsValid)
            {
                SetToastMessage(message: "Please fill in the required fields appropriately.");
                ViewBag.Colleges = _context.College.ToList();

                return View(reportEncodedVM);
            }

            var studentReport = new ReportEncoded
            {
                OffenseId = reportEncodedVM.OffenseId,
                StudentNumber = reportEncodedVM.StudentNumber,
                CollegeID = reportEncodedVM.CollegeID,
                CommissionDate = reportEncodedVM.CommissionDate,
                // FormatorId = reportEncodedVM.FormatorId,
                Course = reportEncodedVM.Course,
                Description = reportEncodedVM.Description,

WSRS-SWAFO/Controllers/StudentViolationController.cs
using Microsoft.AspNetCore.Mvc;

namespace WSRS_SWAFO.Controllers
{
    public class StudentViolationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WSRS-SWAFO/Views/Encode/StudentViolation/Index.cshtml
@model IQueryable<WSRS_SWAFO.ViewModels.StudentsRecordModel>
@{
    Layout = "_StudentViolationLayout";
    ViewData["Title"] = "Student Violation";
}

<div id="first-page">
    <h2>Check for an exisiting violation record</h2>
    <form id="search-student" asp-controller="StudentViolation" asp-action="Search">
        <input class="search-id" autocomplete="firstname" placeholder="Check Student Violation Record" aria-required="true" />
        <button class="iconPad" type="submit">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g clip-path="url(#clip0_173_68)">
                    <path d="M6.41667 11.0833C8.994 11.0833 11.0833 8.994 11.0833 6.41667C11.0833 3.83934 8.994 1.75 6.41667 1.75C3.83934 1.75 1.75 3.83934 1.75 6.41667C1.75 8.994 3.83934 11.0833 6.41667 11.0833Z" stroke="#1E1F20" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M12.25 12.25L9.71252 9.71249" stroke="#1E1F20" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </g>
                <defs>
                    <clipPath id="clip0_173_68">
                        <rect width="14" height="14" fill="white" />
                    </clipPath>
                </defs>
            </svg>
        </button>
    </form>
    <table>
        <thead>
            <tr>
                <th>Student Number</th>
                <th>Last Name</th>
                <th>First Name</th>
            </tr>
        </thead>
        <tbody>
            @if (Model == null || !Model.Any())
            {
                <tr>
                    <td colspan="3">No records found.</td>
                </tr>
            }
            else
            {
                foreach (var student in Model)
                {
                    <tr>
                        <td>@student.StudentNumber</td>
                        <td>@student.LastName</td>
                        <td>@student.FirstName</td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a class="btn btn-next">
        Next
    </a>
</div>

<div id="create-new">
    <div class="title">
        <a class="btn-back">
            <svg width="32" height="32" viewBox="0 0 43 43" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="21.5" cy="21.5" r="20.5" stroke="black" stroke-width="2" />
                <path d="M16 22L24 14" stroke="black" stroke-width="2" stroke-linecap="round" />
                <path d="M16 22L24 30" stroke="black" stroke-width="2" stroke-linecap="round" />
            </svg>

        </a>
        <h2>Create a New Record</h2>
    </div>
    <div class="input-wrapper">
        <input  type="text" class="input" autocomplete="StudentNumber" aria-required="true" />
        <label  class="label">Student Number<span>*</span></label>
        <span  class="text-danger"></span>
    </div>
    <div class="input-wrapper">
        <input  type="text" class="input" autocomplete="firstname" aria-required="true" />
        <label  class="label">First Name<span>*</span></label>
        <span  class="text-danger"></span>
    </div>
    <div class="input-wrapper">
        <input  type="text" class="input" autocomplete="MiddleInitial" aria-required="true" />
        <label  class="label">Middle Initial<span>*</span></label>
        <span  class="text-danger"></span>
    </div>
    <div class="input-wrapper">
        <input  type="text" class="input" autocomplete="LastName" aria-required="true" />
        <label  class="label">Last Name<span>*</span></label>
        <span  class="text-danger"></span>
    </div>
    <a class="btn btn-next">
        Next
    </a>
</div>

<div id="record-violation">
    <div class="title">
        <a class="btn-back">
            <svg width="32" height="32" viewBox="0 0 43 43" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="21.5" cy="21.5" r="20.5" stroke="black" stroke-width="2" />
                <path d="M16 22L24 14" stroke="black" stroke-width="2" stroke-linecap="round" />
                <path d="M16 22L24 30" stroke="black" stroke-width="2" stroke-linecap="round" />
            </svg>

        </a>
        <h2>Record Violation</h2>
    </div>
    <div class="input-wrapper">
        <input type="text" class="input" autocomplete="CYS" aria-required="true" />
        <label  class="label">CYS<span>*</span></label>
        <span class="text-danger"></span>
    </div>
    <div class="input-wrapper">
        <input type="date" class="input" autocomplete="dateOfCommission" aria-required="true" />
        <label class="label">Date Of Commission<span>*</span></label>
        <span  class="text-danger"></span>
    </div>
    <div class="input-wrapper">
        <label  class="label">Classification Of Offense<span>*</span></label>
        <select  class="input" aria-required="true">
            <option value="">-- Select an option --</option>
        </select>
        <span  class="text-danger"></span>
    </div>
    <div class="input-wrapper">
        <label  class="label">Nature of Offense<span>*</span></label>
        <select   class="input" aria-required="true">
            <option value="">-- Select an option --</option>
        </select>
        <span class="text-danger"></span>
    </div>
    <div class="input-wrapper">
        <input  type="text" class="input" autocomplete="sanction" aria-required="true" />
        <label  class="label">Sanction<span>*</span></label>
        <span class="text-danger"></span>
    </div>
    <div class="input-wrapper">
        <input  type="text" class="input description" autocomplete="description" aria-required="true" />
        <label  class="label">Description</label>
        <span class="text-danger"></span>
    </div>
    <a class="btn btn-submit">
        Submit
    </a>
</div>