WSRS-Formators/Controllers/ReportViolationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using WSRS_Formators.Dtos;
using WSRS_Formators.Models;
using WSRS_Formators.ViewModels;

namespace WSRS_Formators.Controllers
{
    [Authorize]
    public class ReportViolationController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly UserManager<FormatorUser> _userManager;
        private readonly ILogger<HomeController> _logger;

        public ReportViolationController(IHttpClientFactory httpClientFactory, UserManager<FormatorUser> userManager, ILogger<HomeController> logger)
        {
            _httpClientFactory = httpClientFactory;
            _userManager = userManager;
            _logger = logger;
        }

        [HttpGet]
        public async Task<ActionResult> Index(
            [FromQuery] int? studentNumber)
        {
            if (studentNumber == null)
            {
                return View(new StudentViolationsViewModel());
            }

            var client = _httpClientFactory.CreateClient("WSRS_Api");

            try
            {
                var response = await client.GetAsync($"violations/{studentNumber}");

                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadFromJsonAsync<AllReportsDto>();

                    if (data.Student == null) return View(new StudentViolationsViewModel
                    {
                        StudentNumber = studentNumber
                    });

                    var violations = new StudentViolationsViewModel
                    {
                        StudentNumber = data.Student.StudentNumber,
                        FirstName = data.Student.FirstName,
                        LastName = data.Student.LastName,
                        Violations = data.Violations,
                        TrafficViolations = data.TrafficViolations
                    };
                    return View(violations);
                }

                _logger.LogInformation($"Error Status: {response.StatusCode}");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong getting the requested data. {ex.Message}");
            }

            // Something went wrong, send an empty output
            return View(new StudentViolationsViewModel());
        }

        [HttpGet]
        public IActionResult Create(
            [FromQuery] int? studentNumber,
            [FromQuery] string? firstName,
            [FromQuery] string? lastName)
        {
            if (studentNumber != null || !string.IsNullOrEmpty(firstName) || !string.IsNullOrEmpty(lastName))
            {
                ViewData["StudentNumber"] = studentNumber;
                ViewData["FirstName"] = firstName;
                ViewData["LastName"] = lastName;

                return View();
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> Create(CreateReportViewModel model)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                ModelState.AddModelError(string.Empty, "Unable to retrieve info of current user.");
                return View(model);
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var reportDto = new ReportPendingDto
            {
                FormatorId = currentUser.EmployeeId,
                Formator = currentUser.FullName,
                ReportDate = model.ReportDate,
                StudentNumber = model.StudentNumber,
                FirstName = model.FirstName,
                LastName = model.LastName,
                College = model.College,
                CourseYearSection = model.CourseYearSection,
                Description = model.Description
            };

            var client = _httpClientFactory.CreateClient("WSRS_Api");

            var response = await client.PostAsJsonAsync("report", reportDto);

            if (response.IsSuccessStatusCode)
            {
                var result = await response.Content.ReadFromJsonAsync<ReportPendingDto>();

                SetToastMessage("Your report has been submitted, thank you.", title: "Success");
                return RedirectToAction(nameof(Index));
            }

            SetToastMessage("Something went wrong submitting your report.", title: "Error", cssClassName: "bg-danger text-white");
            var errorContent = await response.Content.ReadAsStringAsync();
            _logger.LogError("API Response: {StatusCode}, Content: {Content}", response.StatusCode, errorContent);

            return RedirectToAction(nameof(Index));
        }

        private void SetToastMessage(string message, string title = "", string cssClassName = "bg-white")
        {
            var toastMessage = new ToastViewModel
            {
                Title = title,
                Message = message,
                CssClassName = cssClassName
            };
            TempData["Result"] = JsonSerializer.Serialize(toastMessage);
        }
    }
}

WSRS-Formators/Views/Shared/_Layout.cshtml
@using WSRS_Formators.ViewModels
@using System.Text.Json

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DLSU-D Staff Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand text-light" asp-controller="Home" asp-action="Index">DLSU-D Staff Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav flex-grow-1 justify-content-end gap-2">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown">
                            Features
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">-</a></li>
                            <li><a class="dropdown-item" href="#">-</a></li>
                            <li>
                                <a class="dropdown-item" asp-controller="ReportViolation" asp-action="Index">
                                    Report Violation
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            @User.FindFirst("FullName")?.Value.ToUpper()
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Account Settings</a></li>
                            <form asp-controller="Account" asp-action="Logout" method="post">
                            <li><button class="dropdown-item">Logout</button></li>
                            </form>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="toast-container position-fixed bottom-0 start-0 p-3" style="z-index: 1055;">
        @if (TempData["Result"] != null && TempData["Result"] is string messageJson && !string.IsNullOrEmpty(messageJson))
        {
            var message = JsonSerializer.Deserialize<ToastViewModel>(messageJson);

            if (message != null)
            {
                <partial name="_ToastPartial" model="@message" />
            }
        }
    </div>

    <div class="wrapper">
        <div class="container">
            @RenderBody()
        </div>

        <footer class="text-center text-muted">
            <p>© 2025 - Sia, Soria, Villanueva - Capstone Project</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/components/toast.js" asp-asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

WSRS-Formators/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* Optional head section (safe to skip if not defined in view) *@
    @await RenderSectionAsync("CustomHead", required: false)
</head>
<body>
    <main>
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @* Optional scripts section *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WSRS-Formators/Views/Shared/_ToastPartial.cshtml
@using WSRS_Formators.ViewModels

@if (Model != null)
{
    <div id="toast" class="toast align-items-center border-0 shadow w-auto px-2 py-1 fs-6 @Model.CssClassName" role="alert" data-bs-autohide="true" data-bs-delay="8000">
        <div class="d-flex">
            <div class="toast-body">
                @if (!string.IsNullOrEmpty(Model.Title))
                {
                    <strong>@Model.Title! </strong>
                }
                @Model.Message
            </div>
            <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
}