WSRS-SWAFO/Controllers/EncodeController.cs
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using WSRS_SWAFO.Data;
using WSRS_SWAFO.Models;
using WSRS_SWAFO.ViewModels;
using WSRS_SWAFO.Interfaces;
using Hangfire;
using WSRS_SWAFO.Data.Enum;
using WSRS_SWAFO.Dtos;

namespace WSRS_SWAFO.Controllers
{
    [Authorize(Roles = "AppRole.Admin")]
    public class EncodeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<EncodeController> _logger;
        private readonly IEmailSender _emailSender;
        private readonly IHttpClientFactory _httpClientFactory;

        public EncodeController(ApplicationDbContext context, ILogger<EncodeController> logger, IEmailSender emailSender, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _logger = logger;
            _emailSender = emailSender;
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(EncodingMode));
        }

        // Mode Switch
        // Ticks whether Student Violation or Traffic Violation
        public IActionResult EncodingMode()
        {
            var referer = Request.Headers["Referer"].ToString();
            if (string.IsNullOrEmpty(referer))
            {
                return Content("<script>alert('External links are disabled. Use the in-app interface to proceed.'); window.history.back();</script>", "text/html");
            }
            return View();
        }

        // Page One - Student Violation Controller
        // Checks Student Record Database upon page load - Index
        [HttpPost]
        [HttpGet] // Adding for optional
        public async Task<IActionResult> StudentRecordViolation(string violationType = null)
        {
            if (HttpContext.Request.Method == HttpMethods.Post)
            {
                // Store the violation type in session or view data if needed
                HttpContext.Session.SetString("ViolationType", violationType);
            }

            // Checks student data in the Database
            var students = await _context.Students
                .Select(student => new StudentRecordViewModel
                {
                    // For every student in the Database, compiler creates the query
                    StudentNumber = student.StudentNumber,
                    LastName = student.LastName,
                    FirstName = student.FirstName
                })
                .AsNoTracking()
                .Take(5)
                .ToListAsync();

            TempData["ViolationType"] = violationType; // for pill indicator
            // Returns queried list
            return View(students.AsQueryable());
        }

        // Search Student - GET Function
        [HttpGet]
        public IActionResult Search(string searchStudent)
        {
            // Checks searchStudent
            if (!string.IsNullOrEmpty(searchStudent))
            {
                var studentsQuery = _context.Students.AsQueryable();
                // Compiler creates query for searchStudent
                if (int.TryParse(searchStudent, out int studentNumber))
                {
                    studentsQuery = studentsQuery.Where(s => s.StudentNumber == studentNumber);
                }
                else
                {
                    studentsQuery = studentsQuery.Where(s => s.LastName.Contains(searchStudent) || s.FirstName.Contains(searchStudent));
                }

                // Once existed, compiler creates table query
                var ExistingStudent = studentsQuery.Select(s => new StudentRecordViewModel
                {
                    StudentNumber = s.StudentNumber,
                    LastName = s.LastName,
                    FirstName = s.FirstName
                });
                return View(nameof(StudentRecordViolation), ExistingStudent);
            }
            return View(nameof(StudentRecordViolation), null);
        }

        // Page 2 - Create Student Data (If no student present) - Index
        [HttpGet]
        public IActionResult CreateStudentRecord(
            int? studentNumber,
            string? firstName,
            string? lastName)
        {
            var referer = Request.Headers["Referer"].ToString();
            if (string.IsNullOrEmpty(referer))
            {
                return RedirectToAction(nameof(StudentRecordViolation));
            }

            if (HttpContext.Session.GetString("ViolationType") is string violationType &&
                violationType == "Traffic Violation")
            {
                TempData["FromTraffic"] = true;
            }

            return View();
        }

        // Create Student Entry - POST Function
        [HttpPost]
        public async Task<IActionResult> CreateNewStudent(StudentRecordViewModel model, bool fromPending = false, bool fromTraffic = false)
        {
            if (!ModelState.IsValid)
            {
                SetToastMessage(message: "Please fill in the required fields appropriately.");
                return View(nameof(CreateStudentRecord), model);
            }

            var student = new Student
            {
                StudentNumber = model.StudentNumber,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email.ToLower()
            };

            try
            {
                _context.Students.Add(student);
                await _context.SaveChangesAsync();
                SetToastMessage(title: "Success", message: "A student was registered successfully.");
            }
            catch (Exception ex)
            {
                SetToastMessage(title: "Error", message: "Something went wrong while submitting your data.", cssClassName: "bg-danger text-white");
                _logger.LogError(ex.Message);
            }

            if (fromPending)
            {
                return RedirectToAction(nameof(Pending));
            }

            var redirect = fromTraffic ? nameof(EncodeTrafficViolation) : nameof(EncodeStudentViolation);

            return RedirectToAction(redirect, new
            {
                studentNumber = student.StudentNumber,
                firstName = student.FirstName,
                lastName = student.LastName
            });
        }

        // Checks whether studentID is existing or not - POST, GET Function
        [AcceptVerbs("GET", "POST")]
        public async Task<IActionResult> CheckStudentID(StudentRecordViewModel model)
        {
            var exists = await _context.Students.AnyAsync(student => student.StudentNumber == model.StudentNumber);
            return Json(!exists);
        }

        public IActionResult RedirectToView(
            [FromQuery] int studentNumber,
            [FromQuery] string firstName,
            [FromQuery] string lastName)
        {
            var violationType = HttpContext.Session.GetString("ViolationType");

            if (string.IsNullOrEmpty(violationType))
            {
                return RedirectToAction(nameof(EncodingMode));
            }

            if (violationType == "Student Violation")
            {
                return RedirectToAction(nameof(EncodeStudentViolation), new
                {
                    studentNumber,
                    firstName,
                    lastName
                });
            }

            if (violationType == "Traffic Violation")
            {
                return RedirectToAction(nameof(EncodeTrafficViolation), new
                {
                    studentNumber,
                    firstName,
                    lastName
                });
            }

            // Redirect to first page if no mode is selected
            return RedirectToAction(nameof(EncodingMode));
        }

        // Page 3 - Encode Student Violation (If student data exist)
        public IActionResult EncodeStudentViolation(
            [FromQuery] int studentNumber,
            [FromQuery] string firstName,
            [FromQuery] string lastName,
            [FromQuery] string? course = null,
            [FromQuery] string? collegeId = null,
            [FromQuery] string? note = null)
        {
            var referer = Request.Headers["Referer"].ToString();
            if (string.IsNullOrEmpty(referer))
            {
                return RedirectToAction(nameof(StudentRecordViolation));
            }

            var studentInfo = new ReportEncodedViewModel
            {
                StudentNumber = studentNumber,
                FirstName = firstName,
                LastName = lastName,
                Course = course,
                CollegeID = collegeId,
                Note = note,
            };

            ViewBag.Colleges = _context.College.ToList();

            return View(studentInfo);
        }

        // Creates a violation record - POST Function
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EncodeStudentViolation(ReportEncodedViewModel reportEncodedVM)
        {
            if (!ModelState.IsValid)
            {
                SetToastMessage(message: "Please fill in the required fields appropriately.");
                ViewBag.Colleges = _context.College.ToList();

                return View(reportEncodedVM);
            }

            var studentReport = new ReportEncoded
            {
                OffenseId = reportEncodedVM.OffenseId,
                StudentNumber = reportEncodedVM.StudentNumber,
                CollegeID = reportEncodedVM.CollegeID,
                CommissionDate = reportEncodedVM.CommissionDate,
                // FormatorId = reportEncodedVM.FormatorId,
                Course = reportEncodedVM.Course,
                Description = reportEncodedVM.Description,

WSRS-SWAFO/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/dashboardStyle.css" asp-append-version="true" />
</head>
<body>
    <partial name="_SidebarPartial" />
    <div class="container">
        <main>
            @RenderBody()
        </main>
        <partial name="_FooterPartial"/>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WSRS-SWAFO/Views/Shared/_EncodeLayout.cshtml
@using System.Text.Json
@using WSRS_SWAFO.ViewModels
@using WSRS_SWAFO.Helpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/SWAFO-LOGO.ico" />
    @RenderSection("customHead", required: false)
</head>
<body>
    <partial name="_SidebarPartial" />

    <div class="container">
        <main>
            <div id="encode">
                <h1>Encode</h1>
                <div id="category-function">
                    <a asp-controller="Encode" asp-action="EncodingMode" class="student-encode btn">
                        Encode Violation
                    </a>
                    @if (await NetworkHelper.IsOnline() == true)
                    {
                        <a asp-controller="Encode" asp-action="Pending" class="pending-encode btn">
                            Pending
                        </a>
                        <a asp-controller="Encode" asp-action="GMCRequests" class="gmc-request-encode btn">
                            GMC Requests
                        </a>
                    }
                </div>
                <hr>
                @RenderBody()
            </div>
        </main>
        <footer>
            <div class="f-medium">Student Welfare and Formation Office Record System</div>
            <span>All Rights Reserved</span>
        </footer>
    </div>

    <div class="toast-container position-fixed bottom-0 start-0 p-3" style="z-index: 1055;">
        @if (TempData["Result"] != null && TempData["Result"] is string messageJson && !string.IsNullOrEmpty(messageJson))
        {
            var message = JsonSerializer.Deserialize<ToastViewModel>(messageJson);

            if (message != null)
            {
                <partial name="_ToastPartial" model="@message" />
            }
        }
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/encode.js"></script>
    <script src="~/js/components/toast.js" asp-asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WSRS-SWAFO/Views/Shared/_FooterPartial.cshtml
<footer>
    <div class="f-medium">Student Welfare and Formation Office Record System</div>
    <span>All Rights Reserved</span>
</footer>

WSRS-SWAFO/Views/Shared/_Layout.cshtml
@using System.Text.Json
@using WSRS_SWAFO.ViewModels

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/SWAFO-LOGO.ico" />
    @RenderSection("customHead", required: false)
</head>
<body>
    <partial name="_SidebarPartial" />
    <div class="container">
        <main>
            @RenderBody()
        </main>
        <partial name="_FooterPartial" />
    </div>

    <!-- Normal Toast -->
    <div class="toast-container position-fixed bottom-0 start-0 p-3" style="z-index: 1055;">
        @if (TempData["Result"] != null && TempData["Result"] is string messageJson && !string.IsNullOrEmpty(messageJson))
        {
            var message = JsonSerializer.Deserialize<ToastViewModel>(messageJson);

            if (message != null)
            {
                <partial name="_ToastPartial" model="@message" />
            }
        }
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/components/toast.js" asp-append-version="true"></script>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

WSRS-SWAFO/Views/Shared/_LogOnLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SWAFO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/logOnStyle.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/SWAFO-LOGO.ico" />
</head>
<body>
    <div id="logOnPanel">
            @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WSRS-SWAFO/Views/Shared/_SidebarPartial.cshtml
<!-- Sign Out Modal  -->
<div class="modal fade" id="signOutModal" tabindex="-1" aria-labelledby="signOutModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <h1 class="modal-title fs-2" id="signOutModalLabel">
                    Sign Out
                </h1>
                Are you sure you want to sign out?
            </div>
            <div class="modal-footer">
                <button class="btn" type="button" data-bs-dismiss="modal">
                    No
                </button>
                <form id="signOutForm" asp-controller="LogOn" asp-action="SignOut" method="post">
                    <button class="btn dark-btn" type="submit">
                        Yes
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Sidebar -->
<nav id="sidebar">
    <img src="/assets/img/SWAFO-LOGO.png" class="logo-mini" />
    <div id="sidePanel">
        <div id="sel">
            <a asp-controller="Dashboard" asp-action="Index" class="dashboard-nav">
                <svg class="icons" width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                    d="M1 10.5H7C7.55 10.5 8 10.05 8 9.5V1.5C8 0.95 7.55 0.5 7 0.5H1C0.45 0.5 0 0.95 0 1.5V9.5C0 10.05 0.45 10.5 1 10.5ZM1 18.5H7C7.55 18.5 8 18.05 8 17.5V13.5C8 12.95 7.55 12.5 7 12.5H1C0.45 12.5 0 12.95 0 13.5V17.5C0 18.05 0.45 18.5 1 18.5ZM11 18.5H17C17.55 18.5 18 18.05 18 17.5V9.5C18 8.95 17.55 8.5 17 8.5H11C10.45 8.5 10 8.95 10 9.5V17.5C10 18.05 10.45 18.5 11 18.5ZM10 1.5V5.5C10 6.05 10.45 6.5 11 6.5H17C17.55 6.5 18 6.05 18 5.5V1.5C18 0.95 17.55 0.5 17 0.5H11C10.45 0.5 10 0.95 10 1.5Z"
                    fill="currentColor" />
                </svg>
                <div>Dashboard</div>
            </a>
            @if (User.IsInRole("AppRole.Admin"))
            {
                <a asp-controller="Encode" asp-action="EncodingMode" class="encode-nav">
                    <svg class="icons" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                        d="M18 7.5V6.5L12 0.5H2C0.89 0.5 0 1.39 0 2.5V16.5C0 17.0304 0.210714 17.5391 0.585786 17.9142C0.960859 18.2893 1.46957 18.5 2 18.5H8V16.63L16.39 8.24C16.83 7.8 17.39 7.56 18 7.5ZM11 2L16.5 7.5H11V2ZM19.85 11.69L18.87 12.67L16.83 10.63L17.81 9.65C18 9.45 18.33 9.45 18.53 9.65L19.85 10.97C20.05 11.17 20.05 11.5 19.85 11.69ZM16.13 11.33L18.17 13.37L12.04 19.5H10V17.46L16.13 11.33Z"
                        fill="currentColor" />
                    </svg>
                    <div>Encode</div>
                </a>
            }
            @if (User.IsInRole("AppRole.Admin") || User.IsInRole("AppRole.Member"))
            {
                <a asp-controller="Records" asp-action="Index" class="records-nav">
                    <svg class="icons" width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                        d="M16.5 0.5H1.5C1.10218 0.5 0.720644 0.658035 0.43934 0.93934C0.158035 1.22064 0 1.60218 0 2V17C0 17.3978 0.158035 17.7794 0.43934 18.0607C0.720644 18.342 1.10218 18.5 1.5 18.5H11.6897C11.8867 18.5003 12.0818 18.4616 12.2638 18.3862C12.4458 18.3107 12.611 18.2 12.75 18.0603L17.5603 13.25C17.7 13.111 17.8107 12.9458 17.8862 12.7638C17.9616 12.5818 18.0003 12.3867 18 12.1897V2C18 1.60218 17.842 1.22064 17.5607 0.93934C17.2794 0.658035 16.8978 0.5 16.5 0.5ZM6 5.75H12C12.1989 5.75 12.3897 5.82902 12.5303 5.96967C12.671 6.11032 12.75 6.30109 12.75 6.5C12.75 6.69891 12.671 6.88968 12.5303 7.03033C12.3897 7.17098 12.1989 7.25 12 7.25H6C5.80109 7.25 5.61032 7.17098 5.46967 7.03033C5.32902 6.88968 5.25 6.69891 5.25 6.5C5.25 6.30109 5.32902 6.11032 5.46967 5.96967C5.61032 5.82902 5.80109 5.75 6 5.75ZM9 13.25H6C5.80109 13.25 5.61032 13.171 5.46967 13.0303C5.32902 12.8897 5.25 12.6989 5.25 12.5C5.25 12.3011 5.32902 12.1103 5.46967 11.9697C5.61032 11.829 5.80109 11.75 6 11.75H9C9.19891 11.75 9.38968 11.829 9.53033 11.9697C9.67098 12.1103 9.75 12.3011 9.75 12.5C9.75 12.6989 9.67098 12.8897 9.53033 13.0303C9.38968 13.171 9.19891 13.25 9 13.25ZM6 10.25C5.80109 10.25 5.61032 10.171 5.46967 10.0303C5.32902 9.88968 5.25 9.69891 5.25 9.5C5.25 9.30109 5.32902 9.11032 5.46967 8.96967C5.61032 8.82902 5.80109 8.75 6 8.75H12C12.1989 8.75 12.3897 8.82902 12.5303 8.96967C12.671 9.11032 12.75 9.30109 12.75 9.5C12.75 9.69891 12.671 9.88968 12.5303 10.0303C12.3897 10.171 12.1989 10.25 12 10.25H6ZM12 16.6897V12.5H16.1906L12 16.6897Z"
                        fill="currentColor" />
                    </svg>
                    <div>Records</div>
                </a>
                <a asp-controller="Reports" asp-action="Index" class="reports-nav">
                    <svg class="icons" width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                        d="M16 0.5H2C0.9 0.5 0 1.4 0 2.5V16.5C0 17.6 0.9 18.5 2 18.5H16C17.1 18.5 18 17.6 18 16.5V2.5C18 1.4 17.1 0.5 16 0.5ZM6 14.5H4V7.5H6V14.5ZM10 14.5H8V4.5H10V14.5ZM14 14.5H12V10.5H14V14.5Z"
                        fill="currentColor" />
                    </svg>
                    <div>Reports</div>
                </a>

                @if (User.IsInRole("AppRole.Admin"))
                {
                    <a asp-controller="Calendar" asp-action="CalendarView" class="calendar-nav">
                        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M12 8.1V9.9H14V8.1H12ZM8 8.1V9.9H10V8.1H8ZM4 8.1V9.9H6V8.1H4ZM2 1.8C1.46957 1.8 0.96086 1.98964 0.585787 2.32721C0.210714 2.66477 0 3.12261 0 3.6V16.2C0 16.6774 0.210714 17.1352 0.585787 17.4728C0.96086 17.8104 1.46957 18 2 18H16C16.5304 18 17.0391 17.8104 17.4142 17.4728C17.7893 17.1352 18 16.6774 18 16.2V3.6C18 3.12261 17.7893 2.66477 17.4142 2.32721C17.0391 1.98964 16.5304 1.8 16 1.8H15V0H13V1.8H5V0H3V1.8H2ZM2 16.2V6.3H16V16.2H2ZM12 11.7V13.5H14V11.7H12ZM8 11.7V13.5H10V11.7H8ZM4 11.7V13.5H6V11.7H4Z" fill="currentColor" />
                        </svg>

                        <div>Calendar</div>
                    </a>
                }

                <a asp-controller="Account" asp-action="Index" class="account-nav">
                    <svg class="icons" width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            d="M16 0.5H2C0.9 0.5 0 1.4 0 2.5V16.5C0 17.6 0.9 18.5 2 18.5H16C17.1 18.5 18 17.6 18 16.5V2.5C18 1.4 17.1 0.5 16 0.5ZM9 3.5C10.93 3.5 12.5 5.07 12.5 7C12.5 8.93 10.93 10.5 9 10.5C7.07 10.5 5.5 8.93 5.5 7C5.5 5.07 7.07 3.5 9 3.5ZM16 16.5H2V16.27C2 15.65 2.28 15.07 2.76 14.69C4.47 13.32 6.64 12.5 9 12.5C11.36 12.5 13.53 13.32 15.24 14.69C15.72 15.07 16 15.66 16 16.27V16.5Z"
            fill="currentColor" />
        </svg>
        <div>Account</div>
      </a>
      }
    </div>
    <div id="logout">
      <hr />
      <button type="button" data-bs-toggle="modal" data-bs-target="#signOutModal">
        <svg class="icons" width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            d="M11.7224 10.2641L8.37063 13.8641C8.18173 14.067 7.92553 14.181 7.65839 14.181C7.39125 14.181 7.13505 14.067 6.94615 13.8641C6.75725 13.6612 6.65113 13.386 6.65113 13.0991C6.65113 12.8122 6.75725 12.537 6.94615 12.3341L8.58095 10.58H1.62612C1.35944 10.58 1.10369 10.4662 0.915115 10.2637C0.726544 10.0611 0.620605 9.78643 0.620605 9.5C0.620605 9.21357 0.726544 8.93886 0.915115 8.73633C1.10369 8.53379 1.35944 8.42 1.62612 8.42H8.58095L6.94782 6.6641C6.85429 6.56364 6.7801 6.44437 6.72948 6.31311C6.67886 6.18186 6.6528 6.04117 6.6528 5.8991C6.6528 5.61217 6.75892 5.33699 6.94782 5.1341C7.13672 4.93121 7.39292 4.81723 7.66006 4.81723C7.92721 4.81723 8.18341 4.93121 8.37231 5.1341L11.724 8.7341C11.8177 8.83455 11.8919 8.95387 11.9425 9.08521C11.9931 9.21655 12.0191 9.35733 12.0189 9.49947C12.0188 9.64162 11.9925 9.78233 11.9416 9.91354C11.8907 10.0448 11.8162 10.1639 11.7224 10.2641ZM16.3737 0.5H11.011C10.7443 0.5 10.4885 0.613785 10.2999 0.816325C10.1114 1.01886 10.0054 1.29357 10.0054 1.58C10.0054 1.86643 10.1114 2.14114 10.2999 2.34368C10.4885 2.54621 10.7443 2.66 11.011 2.66H15.3682V16.34H11.011C10.7443 16.34 10.4885 16.4538 10.2999 16.6563C10.1114 16.8589 10.0054 17.1336 10.0054 17.42C10.0054 17.7064 10.1114 17.9811 10.2999 18.1837C10.4885 18.3862 10.7443 18.5 11.011 18.5H16.3737C16.6404 18.5 16.8961 18.3862 17.0847 18.1837C17.2733 17.9811 17.3792 17.7064 17.3792 17.42V1.58C17.3792 1.29357 17.2733 1.01886 17.0847 0.816325C16.8961 0.613785 16.6404 0.5 16.3737 0.5Z"
            fill="currentColor" />
        </svg>
        <div>Sign Out</div>
      </button>
    </div>
  </div>
</nav>

WSRS-SWAFO/Views/Shared/_StudentModalPartial.cshtml
<div class="modal fade" id="studentModal" tabindex="-1" aria-labelledby="studentModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl modal-fullscreen-lg-down">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body m-2"></div>
        </div>
    </div>
</div>

WSRS-SWAFO/Views/Shared/_StudentViolationLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/studentViolationStyle.css" asp-append-version="true" />
</head>
<body onload="formInitializer()">
    <partial name="_SidebarPartial" />
    <section>
        <main class="container">
            <div id="encode">
                <h1>Encode</h1>
                <div id="category-function">
                    <a asp-controller="Encode" asp-action="Index" class="student-encode">
                        Student Violation
                    </a>
                    <a class="traffic-encode">
                        Traffic Violation
                    </a>
                    <a class="pending-encode">
                        Pending
                    </a>
                </div>
                <hr>
                <div class="content-panel student-violation">
                    <div id="input-panel">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </main>
        <partial name="_FooterPartial" />
    </section>
    <script src="~/js/studentViolation.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>